export const ADD_USER_REQUEST = "ADD_USER_REQUEST ";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS ";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE ";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST ";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS ";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE ";
